version: '3.8'

services:
  api:
    image: ebarakoji/plant-reminder:v1.0
    build: .
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./data:/app/data
    command: 'python src/main.py'
